# Use root/example as user/password credentials
version: '3.1'

services:

  car:
    image: almirjr94/car-service:0.0.1
    container_name: car
    restart: always
    ports:
      - "9091:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_PASSWORD: example
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_HOST: mongo


  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/